"""adjust updateAt for auto update into users table

Revision ID: 87e0c27ff51c
Revises: 2ae39ba8ff61
Create Date: 2024-10-04 11:36:23.232732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87e0c27ff51c'
down_revision: Union[str, None] = '2ae39ba8ff61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
